package_update: false
packages:
 - curl
 - wget

runcmd:
 - curl -o mega-deploy.sh https://raw.githubusercontent.com/mistio/kubernetes-blueprint/master/scripts/mega-deploy.sh
 - chmod +x mega-deploy.sh
 - ./mega-deploy.sh
